###
# Candidatos
###

# @name getAllCandidates
GET http://localhost:8080/candidatos

###

# @name getCandidateById
GET http://localhost:8080/candidatos/2

###

# @name createCandidate
POST http://localhost:8080/candidatos
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "email": "ada@lovelace.com",
  "description": "Programadora pioneira",
  "state": "SP",
  "cep": "12345-678",
  "skills": ["Lógica", "Matemática", "Computação"],
  "cpf": "123.456.789-00",
  "age": 30,
  "personalDescription": "Interessada em algoritmos",
  "education": "Ciência da Computação",
  "experience": "5 anos de experiência com Node.js e React",
  "password": "senha123",
  "country": "Brasil"
}

###

# @name updateCandidate
PUT http://localhost:8080/candidatos/10
Content-Type: application/json

{
  "name": "Ada Lovelace2",
  "skills": ["Python", "Algoritmos"],
  "age": 31,
  "education": "Engenharia de Computação",
  "experience": "6 anos de experiência"
}

###

# @name deleteCandidate
DELETE http://localhost:8080/candidatos/8

###
# Empresas
###

# @name getAllCompanies
GET http://localhost:8080/empresas

###

# @name getCompanyById
GET http://localhost:8080/empresas/5

###

# @name createCompany
POST http://localhost:8080/empresas
Content-Type: application/json

{
  "name": "TechCorp",
  "email": "contato@techcorp.com",
  "password": "senha123",
  "cnpj": "12.345.678/0001-99",
  "description": "Empresa de tecnologia especializada em software",
  "country": "Brasil",
  "state": "SP",
  "cep": "12345-678"
}

###

# @name updateCompany
PUT http://localhost:8080/empresas/8
Content-Type: application/json

{
  "name": "TechCorp Updated",
  "description": "Atualização da descrição da empresa",
  "country": "Brasil",
  "password": "novaSenha123"
}

###

# @name deleteCompany
DELETE http://localhost:8080/empresas/6

###
# Vagas
###

# @name getAllVacancies
GET http://localhost:8080/vagas

###

# @name getVacancyById
GET http://localhost:8080/vagas/1

###

# @name createVacancy
POST http://localhost:8080/vagas
Content-Type: application/json

{
  "companyId": 2,
  "title": "Desenvolvedor Backend",
  "description": "Desenvolvimento de APIs com Node.js",
  "location": "Remoto2"
}

###

# @name updateVacancy
PUT http://localhost:8080/vagas/1
Content-Type: application/json

{
  "companyId": 1,
  "title": "Desenvolvedor Fullstack Junior",
  "description": "Desenvolvimento de APIs com Node.js",
  "location": "Remoto"
}

###

# @name deleteVacancy
DELETE http://localhost:8080/vagas/13

###
# Likes
###

# @name candidateLikesVacancy
POST http://localhost:8080/likes/candidate-likes-vacancy
Content-Type: application/x-www-form-urlencoded

candidateId=2&vacancyId=3

###

# @name candidateLikesCompany
POST http://localhost:8080/likes/candidate-likes-company
Content-Type: application/x-www-form-urlencoded

candidateId=2&companyId=1

###

# @name companyLikesCandidate
POST http://localhost:8080/likes/company-likes-candidate
Content-Type: application/x-www-form-urlencoded

companyId=1&candidateId=2

###
# @name getAllSkills
GET http://localhost:8080/skills


###
# @name getSkillById
GET http://localhost:8080/skills/1


###
# @name createSkill_TypeScript
POST http://localhost:8080/skills 
Content-Type: application/json

{ "name": "AWS" }

###
# @name updateSkill
PUT http://localhost:8080/skills/1 
Content-Type: application/json

{ "name": "Java 17" }

###
# @name deleteSkill
DELETE http://localhost:8080/skills/9

### Candidatos (Associação de Skills)

# @name addSkillToCandidate
# Associa a Skill com ID 1 ao Candidato com ID 5
POST http://localhost:8080/candidatos/2/skills 
Content-Type: application/json

{ "skillId": 4 }

###
# @name addAnotherSkillToCandidate
#Associa a Skill com ID 2 ao Candidato com ID 5
POST http://localhost:8080/candidatos/5/skills 
Content-Type: application/json

{ "skillId": 2 }

###
# @name getCandidateSkills
#Lista apenas as skills do candidato 5
GET http://localhost:8080/candidatos/5/skills

###
# @name removeSkillFromCandidate
#Remove a Skill 1 do Candidato 5
DELETE http://localhost:8080/candidatos/5/skills 
Content-Type: application/json

{ "skillId": 1 }

###
###Vagas (Associação de Skills)
# @name addSkillToVacancy
#Define que a Vaga 1 EXIGE a Skill 1
POST http://localhost:8080/vagas/1/skills 
Content-Type: application/json

{ "skillId": 1 }

###
# @name addAnotherSkillToVacancy
#Define que a Vaga 1 TAMBÉM EXIGE a Skill 2
POST http://localhost:8080/vagas/1/skills 
Content-Type: application/json

{ "skillId": 2 }

###
# @name getVacancySkills
#Lista as skills exigidas pela vaga 1
GET http://localhost:8080/vagas/1/skills

###
# @name removeSkillFromVacancy
#Remove a exigência da Skill 1 na Vaga 1
DELETE http://localhost:8080/vagas/1/skills 
Content-Type: application/json

{ "skillId":7 }

###
# AFINIDADE (Linketinder Inteligente)
###

# @name getVacanciesWithAffinity
# Lista todas as vagas, mostrando a % de match com o Candidato 5
GET http://localhost:8080/vagas/afinidade/2